version: 1.0.1.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore SAIS-CSharp.sln
build:
  project: SAIS-CSharp.sln
  verbosity: minimal
test: off
artifacts:
- path: bin\Release\SAIS-CSharp*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Ggkz3LuVG+Bsykyisf0ptmatdvwIizkXhsPpPGSUW4B2y7XHuSAHMwJWk/ScGYSO
  skip_symbols: true
notifications:
- provider: Email
  to:
  - bryson.gibbons@pnnl.gov
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true